package com.myrts.map;

import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.badlogic.gdx.utils.Array;
import org.poly2tri.triangulation.TriangulationPoint;
import org.poly2tri.triangulation.delaunay.DelaunayTriangle;
import org.poly2tri.triangulation.point.TPoint;

public class NavMeshRenderer {

    /**
     * Draws the triangles of a NavMesh generated by Poly2Tri.
     * IMPORTANT: The caller MUST have already called shapeRenderer.begin(ShapeType.Line)
     * before using this method!
     * * @param shapeRenderer The ShapeRenderer to use for drawing.
     *
     * @param triangles The list of DelaunayTriangle objects to draw.
     */
    public static void drawDelaunay(ShapeRenderer shapeRenderer, Array<DelaunayTriangle> triangles) {
        if (triangles == null || triangles.isEmpty()) {
            return; // Nothing to draw
        }

        // We no longer call begin() here!

        shapeRenderer.setColor(Color.CYAN);

        // Loop through each triangle and draw its three edges
        for (DelaunayTriangle tri : triangles) {
            TriangulationPoint p1 = tri.points[0];
            TriangulationPoint p2 = tri.points[1];
            TriangulationPoint p3 = tri.points[2];
            shapeRenderer.line(p1.getXf(), p1.getYf(), p2.getXf(), p2.getYf());
            shapeRenderer.line(p2.getXf(), p2.getYf(), p3.getXf(), p3.getYf());
            shapeRenderer.line(p3.getXf(), p3.getYf(), p1.getXf(), p1.getYf());
        }

        // We no longer call end() here!
    }

    public static void drawCentroidLinks(ShapeRenderer shapeRenderer, Array<DelaunayTriangle> triangles) {
        if (triangles == null || triangles.isEmpty()) return;

        shapeRenderer.setColor(Color.YELLOW);

        for (DelaunayTriangle tri : triangles) {
            float cx1 = (float) tri.centroid().getX();
            float cy1 = (float) tri.centroid().getY();

            for (int i = 0; i < 3; i++) {
                // Check that the neighbor exists AND the edge is NOT constrained (blocked)
                if (tri.neighbors[i] != null) {
                    float cx2 = (float) tri.neighbors[i].centroid().getX();
                    float cy2 = (float) tri.neighbors[i].centroid().getY();

                    shapeRenderer.line(cx1, cy1, cx2, cy2);
                }
            }
        }
    }

    /**
     * Draws tick marks in the center of a triangle based on how many neighbors it has.
     * Ensure that shapeRenderer.begin(ShapeType.Line) has been called before using this.
     *
     * @param triangles The triangle array to evaluate and draw in.
     * @param shapeRenderer The ShapeRenderer used for drawing.
     */
    public static void drawNeighborTickMarks( ShapeRenderer shapeRenderer, Array<DelaunayTriangle> triangles) {
        // Count the number of non-null neighbors
        shapeRenderer.setColor(Color.YELLOW);
        for (DelaunayTriangle triangle : triangles) {
            int neighborCount = 0;
            for (int i = 0; i < 3; i++) {
                if (triangle.neighbors[i] != null) {
                    neighborCount++;
                }
            }

            // If it has no neighbors, we don't draw anything
            if (neighborCount == 0) return;

            // Get the center of the triangle
            TPoint centroid = triangle.centroid();
            float cx = (float) centroid.getX();
            float cy = (float) centroid.getY();

            // ** Adjust these values based on your game's world scale! **
            // If your world is 1 unit = 1 pixel, you might want length = 10f, spacing = 4f
            // If your world is 1 unit = 1 tile (e.g., 32px), you might want length = 0.4f, spacing = 0.15f
            float tickLength = 8f;
            float spacing = 3f;
            float halfLength = tickLength / 2f;

            // Draw the tick marks based on the neighbor count
            if (neighborCount == 1) {
                // "I" - One line perfectly centered
                shapeRenderer.line(cx, cy - halfLength, cx, cy + halfLength);
            } else if (neighborCount == 2) {
                // "II" - Two lines offset equally from the center
                float offset = spacing / 2f;
                shapeRenderer.line(cx - offset, cy - halfLength, cx - offset, cy + halfLength);
                shapeRenderer.line(cx + offset, cy - halfLength, cx + offset, cy + halfLength);
            } else if (neighborCount == 3) {
                // "III" - One line centered, one on the left, one on the right
                shapeRenderer.line(cx - spacing, cy - halfLength, cx - spacing, cy + halfLength);
                shapeRenderer.line(cx, cy - halfLength, cx, cy + halfLength);
                shapeRenderer.line(cx + spacing, cy - halfLength, cx + spacing, cy + halfLength);
            }
        }
    }

}
