package com.myrts.map;

import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.badlogic.gdx.utils.Array;
import org.poly2tri.triangulation.TriangulationPoint;
import org.poly2tri.triangulation.delaunay.DelaunayTriangle;

public class NavMeshRenderer {

    /**
     * Draws the triangles of a NavMesh.
     *
     * @param shapeRenderer The ShapeRenderer to use for drawing.
     * @param triangles     The list of Triangle objects to draw.
     */
    public static void draw(ShapeRenderer shapeRenderer, Array<Triangle> triangles) {
        if (triangles == null || triangles.isEmpty()) {
            return; // Nothing to draw
        }

        shapeRenderer.begin(ShapeRenderer.ShapeType.Line);
        shapeRenderer.setColor(Color.GREEN);

        // Loop through each triangle and draw its three edges
        for (Triangle tri : triangles) {
            shapeRenderer.line(tri.p1, tri.p2);
            shapeRenderer.line(tri.p2, tri.p3);
            shapeRenderer.line(tri.p3, tri.p1);
        }

        shapeRenderer.end();
    }

    /**
     * Draws the triangles of a NavMesh generated by Poly2Tri.
     * @param shapeRenderer The ShapeRenderer to use for drawing.
     * @param triangles     The list of DelaunayTriangle objects to draw.
     */
    public static void drawDelaunay(ShapeRenderer shapeRenderer, Array<DelaunayTriangle> triangles) {
        if (triangles == null || triangles.isEmpty()) {
            return; // Nothing to draw
        }

        shapeRenderer.begin(ShapeRenderer.ShapeType.Line);
        shapeRenderer.setColor(Color.CYAN); // Use a different color to see the new navmesh

        // Loop through each triangle and draw its three edges
        for (DelaunayTriangle tri : triangles) {
            TriangulationPoint p1 = tri.points[0];
            TriangulationPoint p2 = tri.points[1];
            TriangulationPoint p3 = tri.points[2];
            shapeRenderer.line(p1.getXf(), p1.getYf(), p2.getXf(), p2.getYf());
            shapeRenderer.line(p2.getXf(), p2.getYf(), p3.getXf(), p3.getYf());
            shapeRenderer.line(p3.getXf(), p3.getYf(), p1.getXf(), p1.getYf());
        }

        shapeRenderer.end();
    }
}
